export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_BUSINESS_HOURS_SUCCESS = "SET_BUSINESS_HOURS_SUCCESS";
export const SET_BUSINESS_HOURS_FAIL = "SET_BUSINESS_HOURS_FAIL";
export const NOT_FIRST_TIME_SUCCESS = "NOT_FIRST_TIME_SUCCESS";
export const NOT_FIRST_TIME_FAIL = "NOT_FIRST_TIME_FAIL";
export const ROLES_SUCCESS = "ROLES_SUCCESS";
export const ROLES_FAIL = "ROLES_FAIL";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_FAIL = "PRODUCT_FAIL"

export const EMPLOYEE_SUCCESS = "EMPLOYEE_SUCCESS";
export const EMPLOYEE_FAIL = "EMPLOYEE_FAIL"